site_name: Education populaire

# theme_dir: 'themes/mkdocs-material/material'
# theme_dir: 'themes/mkdocs-material'

site_author: 'El Gadjo Ridículo'
site_url: 'http://elgadjo.github.io/peer-education'

# copyright: 'Copyright (c) 2016 El Gadjo Ridículo'

repo_name: 'GitHub'
repo_url: 'https://github.com/elgadjo/peer-education'
site_favicon: 'favicon.ico'

theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'orange'
    neutral: 'deep purple'
  i18n:
    prev: 'Chapitre précédent'
    next: 'Chapitre suivant'

extra_css: 
  - css/extra.css

extra_javascript: 
  - js/extra.js

#author:
#  github: 'elgadjo'
#  twitter: 'elgadjo'

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  - toc:
      permalink: '#'
  # - codehilite(css_class=code)

pages: 
- 'Accueil': index.md
- 'Économie': economie.md
- 'Éducation': education.md
- 'Environnement': environnement.md
- 'Identités': identites.md
- 'Monnaie': monnaie.md
- 'Politique': politique.md
- 'Vrac': en_vrac.md

#- 'Écologie': ecologie.md
